// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZWMOvFOM8ysuYw5ZmBVSqcLxxmRzkm2I',
    appId: '1:849341735670:web:ecb130e4f22b9b355642d7',
    messagingSenderId: '849341735670',
    projectId: 'gis-project-bd123',
    authDomain: 'gis-project-bd123.firebaseapp.com',
    storageBucket: 'gis-project-bd123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD14vSY3efiYATRbkVY-2kHCb-mJV1R0M',
    appId: '1:849341735670:android:e50e48b2ebcb0eec5642d7',
    messagingSenderId: '849341735670',
    projectId: 'gis-project-bd123',
    storageBucket: 'gis-project-bd123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGSw01lTlLe8itbRCdNWDexBApc8vBaDk',
    appId: '1:849341735670:ios:82e8c8501aa116625642d7',
    messagingSenderId: '849341735670',
    projectId: 'gis-project-bd123',
    storageBucket: 'gis-project-bd123.appspot.com',
    iosClientId: '849341735670-d3o0bkdooehv2aub2nahapmr74btod9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFlutterMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGSw01lTlLe8itbRCdNWDexBApc8vBaDk',
    appId: '1:849341735670:ios:82e8c8501aa116625642d7',
    messagingSenderId: '849341735670',
    projectId: 'gis-project-bd123',
    storageBucket: 'gis-project-bd123.appspot.com',
    iosClientId: '849341735670-d3o0bkdooehv2aub2nahapmr74btod9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFlutterMap',
  );
}
